# -*- coding: utf-8 -*-
"""ML_Multiple_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1usn6gZtI63ghlkckWUfbUK7F65I5Uz78
"""

import pandas as pd
from sklearn.linear_model import LinearRegression

df = pd.read_excel("/ML_Class.xlsx")

X = df[["x1", "x2"]]
y = df["y"]

model = LinearRegression()
model.fit(X, y)

print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)

print(f"y = {model.intercept_} + {model.coef_[0]}*x1 + {model.coef_[1]}*x2")

x1_new = 3
x2_new = 2
y_pred = model.predict([[x1_new, x2_new]])
print("Predicted y:", y_pred[0])

import pandas as pd

df = pd.read_excel("/ML_Class.xlsx")

x1 = list(df.iloc[:, 0])
x2 = list(df.iloc[:, 1])
y  = list(df.iloc[:, 2])

n = len(x1)

sx1 = sum(x1)
sx2 = sum(x2)
sy = sum(y)

sx1x1 = sum(a*a for a in x1)
sx2x2 = sum(a*a for a in x2)
sx1x2 = sum(x1[i]*x2[i] for i in range(n))
sx1y = sum(x1[i]*y[i] for i in range(n))
sx2y = sum(x2[i]*y[i] for i in range(n))

def det3(a11,a12,a13,a21,a22,a23,a31,a32,a33):
    return (
        a11*(a22*a33 - a23*a32)
        - a12*(a21*a33 - a23*a31)
        + a13*(a21*a32 - a22*a31)
    )

D = det3(
    n,    sx1,   sx2,
    sx1,  sx1x1, sx1x2,
    sx2,  sx1x2, sx2x2
)

Da = det3(
    sy,   sx1,   sx2,
    sx1y, sx1x1, sx1x2,
    sx2y, sx1x2, sx2x2
)

Db1 = det3(
    n,    sy,    sx2,
    sx1,  sx1y,  sx1x2,
    sx2,  sx2y,  sx2x2
)

Db2 = det3(
    n,    sx1,   sy,
    sx1,  sx1x1, sx1y,
    sx2,  sx1x2, sx2y
)

a  = Da / D
b1 = Db1 / D
b2 = Db2 / D

print("a =", a)
print("b1 =", b1)
print("b2 =", b2)

x1_new = 3
x2_new = 2

y_pred = a + b1 * x1_new + b2 * x2_new
print("Predicted y =", y_pred)